test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4184ecd823b50bdf1a306d24a0ad9b5ccd18c103.name = "Upgrade from 1.10.4"